version: 0.2
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      php: 8.2
    commands:
      - echo 'Install Success'
  pre_build:
    on-failure: ABORT
    commands:
      - echo 'Pre-build success'
  build:
    on-failure: ABORT
    commands:
      - echo 'Build success'
  post_build:
    on-failure: ABORT
    commands:
      - echo 'Post Build success'
    